'\" t
.nh
.TH "X86-MANPAGES" "7" "December 2023" "Intel" "Intel x86-64 ISA Manual"
.SH NAME
X86 AND AMD64 INSTRUCTION REFERENCE

Derived from the December 2023 version of the Intel® 64 and IA-32
Architectures Software Developer’s
Manual
\[la]https://software.intel.com/en\-us/download/intel\-64\-and\-ia\-32\-architectures\-sdm\-combined\-volumes\-1\-2a\-2b\-2c\-2d\-3a\-3b\-3c\-3d\-and\-4\[ra]\&.
Last updated 2024-02-18.

.PP
\fBTHIS REFERENCE IS NOT PERFECT.\fP It's been mechanically separated into
distinct files by a dumb script. It may be enough to replace the
official documentation on your weekend reverse engineering project, but
for anything where money is at stake, go get the official and freely
available documentation.

.SH CORE INSTRUCTIONS
.TS
allbox;
l l 
l l .
\fBMnemonic\fP	\fBSummary\fP
AAA	ASCII Adjust After Addition
AAD	T{
ASCII Adjust AX Before Division
T}
AAM	ASCII Adjust AX After Multiply
AAS	T{
ASCII Adjust AL After Subtraction
T}
ADC	Add With Carry
ADCX	T{
Unsigned Integer Addition of Two Operands With Carry Flag
T}
ADD	Add
ADDPD	T{
Add Packed Double Precision Floating-Point Values
T}
ADDPS	T{
Add Packed Single Precision Floating-Point Values
T}
ADDSD	T{
Add Scalar Double Precision Floating-Point Values
T}
ADDSS	T{
Add Scalar Single Precision Floating-Point Values
T}
ADDSUBPD	T{
Packed Double Precision Floating-Point Add/Subtract
T}
ADDSUBPS	T{
Packed Single Precision Floating-Point Add/Subtract
T}
ADOX	T{
Unsigned Integer Addition of Two Operands With Overflow Flag
T}
AESDEC	T{
Perform One Round of an AES Decryption Flow
T}
AESDEC128KL	T{
Perform Ten Rounds of AES Decryption Flow With Key Locker Using 128-BitKey
T}
AESDEC256KL	T{
Perform 14 Rounds of AES Decryption Flow With Key Locker Using 256-Bit Key
T}
AESDECLAST	T{
Perform Last Round of an AES Decryption Flow
T}
AESDECWIDE128KL	T{
Perform Ten Rounds of AES Decryption Flow With Key Locker on 8 BlocksUsing 128-Bit Key
T}
AESDECWIDE256KL	T{
Perform 14 Rounds of AES Decryption Flow With Key Locker on 8 BlocksUsing 256-Bit Key
T}
AESENC	T{
Perform One Round of an AES Encryption Flow
T}
AESENC128KL	T{
Perform Ten Rounds of AES Encryption Flow With Key Locker Using 128-Bit Key
T}
AESENC256KL	T{
Perform 14 Rounds of AES Encryption Flow With Key Locker Using 256-Bit Key
T}
AESENCLAST	T{
Perform Last Round of an AES Encryption Flow
T}
AESENCWIDE128KL	T{
Perform Ten Rounds of AES Encryption Flow With Key Locker on 8 BlocksUsing 128-Bit Key
T}
AESENCWIDE256KL	T{
Perform 14 Rounds of AES Encryption Flow With Key Locker on 8 BlocksUsing 256-Bit Key
T}
AESIMC	T{
Perform the AES InvMixColumn Transformation
T}
AESKEYGENASSIST	T{
AES Round Key Generation Assist
T}
AND	Logical AND
ANDN	Logical AND NOT
ANDNPD	T{
Bitwise Logical AND NOT of Packed Double Precision Floating-Point Values
T}
ANDNPS	T{
Bitwise Logical AND NOT of Packed Single Precision Floating-Point Values
T}
ANDPD	T{
Bitwise Logical AND of Packed Double Precision Floating-Point Values
T}
ANDPS	T{
Bitwise Logical AND of Packed Single Precision Floating-Point Values
T}
ARPL	T{
Adjust RPL Field of Segment Selector
T}
BEXTR	Bit Field Extract
BLENDPD	T{
Blend Packed Double Precision Floating-Point Values
T}
BLENDPS	T{
Blend Packed Single Precision Floating-Point Values
T}
BLENDVPD	T{
Variable Blend Packed Double Precision Floating-Point Values
T}
BLENDVPS	T{
Variable Blend Packed Single Precision Floating-Point Values
T}
BLSI	T{
Extract Lowest Set Isolated Bit
T}
BLSMSK	Get Mask Up to Lowest Set Bit
BLSR	Reset Lowest Set Bit
BNDCL	Check Lower Bound
BNDCN	Check Upper Bound
BNDCU	Check Upper Bound
BNDLDX	T{
Load Extended Bounds Using Address Translation
T}
BNDMK	Make Bounds
BNDMOV	Move Bounds
BNDSTX	T{
Store Extended Bounds Using Address Translation
T}
BOUND	T{
Check Array Index Against Bounds
T}
BSF	Bit Scan Forward
BSR	Bit Scan Reverse
BSWAP	Byte Swap
BT	Bit Test
BTC	Bit Test and Complement
BTR	Bit Test and Reset
BTS	Bit Test and Set
BZHI	T{
Zero High Bits Starting with Specified Bit Position
T}
CALL	Call Procedure
CBW	T{
Convert Byte to Word/Convert Word to Doubleword/Convert Doubleword toQuadword
T}
CDQ	T{
Convert Word to Doubleword/Convert Doubleword to Quadword
T}
CDQE	T{
Convert Byte to Word/Convert Word to Doubleword/Convert Doubleword toQuadword
T}
CLAC	T{
Clear AC Flag in EFLAGS Register
T}
CLC	Clear Carry Flag
CLD	Clear Direction Flag
CLDEMOTE	Cache Line Demote
CLFLUSH	Flush Cache Line
CLFLUSHOPT	Flush Cache Line Optimized
CLI	Clear Interrupt Flag
CLRSSBSY	T{
Clear Busy Flag in a Supervisor Shadow Stack Token
T}
CLTS	T{
Clear Task-Switched Flag in CR0
T}
CLUI	Clear User Interrupt Flag
CLWB	Cache Line Write Back
CMC	Complement Carry Flag
CMOVcc	Conditional Move
CMP	Compare Two Operands
CMPPD	T{
Compare Packed Double Precision Floating-Point Values
T}
CMPPS	T{
Compare Packed Single Precision Floating-Point Values
T}
CMPS	Compare String Operands
CMPSB	Compare String Operands
CMPSD	Compare String Operands
CMPSD (1)	T{
Compare Scalar Double Precision Floating-Point Value
T}
CMPSQ	Compare String Operands
CMPSS	T{
Compare Scalar Single Precision Floating-Point Value
T}
CMPSW	Compare String Operands
CMPXCHG	Compare and Exchange
CMPXCHG16B	Compare and Exchange Bytes
CMPXCHG8B	Compare and Exchange Bytes
COMISD	T{
Compare Scalar Ordered Double Precision Floating-Point Values and Set EFLAGS
T}
COMISS	T{
Compare Scalar Ordered Single Precision Floating-Point Values and Set EFLAGS
T}
CPUID	CPU Identification
CQO	T{
Convert Word to Doubleword/Convert Doubleword to Quadword
T}
CRC32	Accumulate CRC32 Value
CVTDQ2PD	T{
Convert Packed Doubleword Integers to Packed Double Precision Floating-PointValues
T}
CVTDQ2PS	T{
Convert Packed Doubleword Integers to Packed Single Precision Floating-PointValues
T}
CVTPD2DQ	T{
Convert Packed Double Precision Floating-Point Values to Packed DoublewordIntegers
T}
CVTPD2PI	T{
Convert Packed Double Precision Floating-Point Values to Packed Dword Integers
T}
CVTPD2PS	T{
Convert Packed Double Precision Floating-Point Values to Packed Single PrecisionFloating-Point Values
T}
CVTPI2PD	T{
Convert Packed Dword Integers to Packed Double Precision Floating-Point Values
T}
CVTPI2PS	T{
Convert Packed Dword Integers to Packed Single Precision Floating-Point Values
T}
CVTPS2DQ	T{
Convert Packed Single Precision Floating-Point Values to Packed SignedDoubleword Integer Values
T}
CVTPS2PD	T{
Convert Packed Single Precision Floating-Point Values to Packed Double PrecisionFloating-Point Values
T}
CVTPS2PI	T{
Convert Packed Single Precision Floating-Point Values to Packed Dword Integers
T}
CVTSD2SI	T{
Convert Scalar Double Precision Floating-Point Value to Doubleword Integer
T}
CVTSD2SS	T{
Convert Scalar Double Precision Floating-Point Value to Scalar Single PrecisionFloating-Point Value
T}
CVTSI2SD	T{
Convert Doubleword Integer to Scalar Double Precision Floating-Point Value
T}
CVTSI2SS	T{
Convert Doubleword Integer to Scalar Single Precision Floating-Point Value
T}
CVTSS2SD	T{
Convert Scalar Single Precision Floating-Point Value to Scalar Double PrecisionFloating-Point Value
T}
CVTSS2SI	T{
Convert Scalar Single Precision Floating-Point Value to Doubleword Integer
T}
CVTTPD2DQ	T{
Convert with Truncation Packed Double Precision Floating-Point Values toPacked Doubleword Integers
T}
CVTTPD2PI	T{
Convert With Truncation Packed Double Precision Floating-Point Values to PackedDword Integers
T}
CVTTPS2DQ	T{
Convert With Truncation Packed Single Precision Floating-Point Values to PackedSigned Doubleword Integer Values
T}
CVTTPS2PI	T{
Convert With Truncation Packed Single Precision Floating-Point Values to PackedDword Integers
T}
CVTTSD2SI	T{
Convert With Truncation Scalar Double Precision Floating-Point Value to SignedInteger
T}
CVTTSS2SI	T{
Convert With Truncation Scalar Single Precision Floating-Point Value to Integer
T}
CWD	T{
Convert Word to Doubleword/Convert Doubleword to Quadword
T}
CWDE	T{
Convert Byte to Word/Convert Word to Doubleword/Convert Doubleword toQuadword
T}
DAA	T{
Decimal Adjust AL After Addition
T}
DAS	T{
Decimal Adjust AL After Subtraction
T}
DEC	Decrement by 1
DIV	Unsigned Divide
DIVPD	T{
Divide Packed Double Precision Floating-Point Values
T}
DIVPS	T{
Divide Packed Single Precision Floating-Point Values
T}
DIVSD	T{
Divide Scalar Double Precision Floating-Point Value
T}
DIVSS	T{
Divide Scalar Single Precision Floating-Point Values
T}
DPPD	T{
Dot Product of Packed Double Precision Floating-Point Values
T}
DPPS	T{
Dot Product of Packed Single Precision Floating-Point Values
T}
EMMS	Empty MMX Technology State
ENCODEKEY128	T{
Encode 128-Bit Key With Key Locker
T}
ENCODEKEY256	T{
Encode 256-Bit Key With Key Locker
T}
ENDBR32	T{
Terminate an Indirect Branch in 32-bit and Compatibility Mode
T}
ENDBR64	T{
Terminate an Indirect Branch in 64-bit Mode
T}
ENQCMD	Enqueue Command
ENQCMDS	Enqueue Command Supervisor
ENTER	T{
Make Stack Frame for Procedure Parameters
T}
EXTRACTPS	T{
Extract Packed Floating-Point Values
T}
F2XM1	Compute 2x–1
FABS	Absolute Value
FADD	Add
FADDP	Add
FBLD	Load Binary Coded Decimal
FBSTP	Store BCD Integer and Pop
FCHS	Change Sign
FCLEX	Clear Exceptions
FCMOVcc	T{
Floating-Point Conditional Move
T}
FCOM	Compare Floating-Point Values
FCOMI	T{
Compare Floating-Point Values and Set EFLAGS
T}
FCOMIP	T{
Compare Floating-Point Values and Set EFLAGS
T}
FCOMP	Compare Floating-Point Values
FCOMPP	Compare Floating-Point Values
FCOS	Cosine
FDECSTP	Decrement Stack-Top Pointer
FDIV	Divide
FDIVP	Divide
FDIVR	Reverse Divide
FDIVRP	Reverse Divide
FFREE	Free Floating-Point Register
FIADD	Add
FICOM	Compare Integer
FICOMP	Compare Integer
FIDIV	Divide
FIDIVR	Reverse Divide
FILD	Load Integer
FIMUL	Multiply
FINCSTP	Increment Stack-Top Pointer
FINIT	Initialize Floating-Point Unit
FIST	Store Integer
FISTP	Store Integer
FISTTP	Store Integer With Truncation
FISUB	Subtract
FISUBR	Reverse Subtract
FLD	Load Floating-Point Value
FLD1	Load Constant
FLDCW	Load x87 FPU Control Word
FLDENV	Load x87 FPU Environment
FLDL2E	Load Constant
FLDL2T	Load Constant
FLDLG2	Load Constant
FLDLN2	Load Constant
FLDPI	Load Constant
FLDZ	Load Constant
FMUL	Multiply
FMULP	Multiply
FNCLEX	Clear Exceptions
FNINIT	Initialize Floating-Point Unit
FNOP	No Operation
FNSAVE	Store x87 FPU State
FNSTCW	Store x87 FPU Control Word
FNSTENV	Store x87 FPU Environment
FNSTSW	Store x87 FPU Status Word
FPATAN	Partial Arctangent
FPREM	Partial Remainder
FPREM1	Partial Remainder
FPTAN	Partial Tangent
FRNDINT	Round to Integer
FRSTOR	Restore x87 FPU State
FSAVE	Store x87 FPU State
FSCALE	Scale
FSIN	Sine
FSINCOS	Sine and Cosine
FSQRT	Square Root
FST	Store Floating-Point Value
FSTCW	Store x87 FPU Control Word
FSTENV	Store x87 FPU Environment
FSTP	Store Floating-Point Value
FSTSW	Store x87 FPU Status Word
FSUB	Subtract
FSUBP	Subtract
FSUBR	Reverse Subtract
FSUBRP	Reverse Subtract
FTST	TEST
FUCOM	T{
Unordered Compare Floating-Point Values
T}
FUCOMI	T{
Compare Floating-Point Values and Set EFLAGS
T}
FUCOMIP	T{
Compare Floating-Point Values and Set EFLAGS
T}
FUCOMP	T{
Unordered Compare Floating-Point Values
T}
FUCOMPP	T{
Unordered Compare Floating-Point Values
T}
FWAIT	Wait
FXAM	Examine Floating-Point
FXCH	Exchange Register Contents
FXRSTOR	T{
Restore x87 FPU, MMX, XMM, and MXCSR State
T}
FXSAVE	T{
Save x87 FPU, MMX Technology, and SSE State
T}
FXTRACT	T{
Extract Exponent and Significand
T}
FYL2X	Compute y ∗ log2x
FYL2XP1	Compute y ∗ log2(x +1)
GF2P8AFFINEINVQB	T{
Galois Field Affine Transformation Inverse
T}
GF2P8AFFINEQB	T{
Galois Field Affine Transformation
T}
GF2P8MULB	Galois Field Multiply Bytes
HADDPD	T{
Packed Double Precision Floating-Point Horizontal Add
T}
HADDPS	T{
Packed Single Precision Floating-Point Horizontal Add
T}
HLT	Halt
HRESET	History Reset
HSUBPD	T{
Packed Double Precision Floating-Point Horizontal Subtract
T}
HSUBPS	T{
Packed Single Precision Floating-Point Horizontal Subtract
T}
IDIV	Signed Divide
IMUL	Signed Multiply
IN	Input From Port
INC	Increment by 1
INCSSPD	Increment Shadow Stack Pointer
INCSSPQ	Increment Shadow Stack Pointer
INS	Input from Port to String
INSB	Input from Port to String
INSD	Input from Port to String
INSERTPS	T{
Insert Scalar Single Precision Floating-Point Value
T}
INSW	Input from Port to String
INT n	Call to Interrupt Procedure
INT1	Call to Interrupt Procedure
INT3	Call to Interrupt Procedure
INTO	Call to Interrupt Procedure
INVD	Invalidate Internal Caches
INVLPG	Invalidate TLB Entries
INVPCID	T{
Invalidate Process-Context Identifier
T}
IRET	Interrupt Return
IRETD	Interrupt Return
IRETQ	Interrupt Return
JMP	Jump
Jcc	Jump if Condition Is Met
KADDB	ADD Two Masks
KADDD	ADD Two Masks
KADDQ	ADD Two Masks
KADDW	ADD Two Masks
KANDB	Bitwise Logical AND Masks
KANDD	Bitwise Logical AND Masks
KANDNB	Bitwise Logical AND NOT Masks
KANDND	Bitwise Logical AND NOT Masks
KANDNQ	Bitwise Logical AND NOT Masks
KANDNW	Bitwise Logical AND NOT Masks
KANDQ	Bitwise Logical AND Masks
KANDW	Bitwise Logical AND Masks
KMOVB	T{
Move From and to Mask Registers
T}
KMOVD	T{
Move From and to Mask Registers
T}
KMOVQ	T{
Move From and to Mask Registers
T}
KMOVW	T{
Move From and to Mask Registers
T}
KNOTB	NOT Mask Register
KNOTD	NOT Mask Register
KNOTQ	NOT Mask Register
KNOTW	NOT Mask Register
KORB	Bitwise Logical OR Masks
KORD	Bitwise Logical OR Masks
KORQ	Bitwise Logical OR Masks
KORTESTB	OR Masks and Set Flags
KORTESTD	OR Masks and Set Flags
KORTESTQ	OR Masks and Set Flags
KORTESTW	OR Masks and Set Flags
KORW	Bitwise Logical OR Masks
KSHIFTLB	Shift Left Mask Registers
KSHIFTLD	Shift Left Mask Registers
KSHIFTLQ	Shift Left Mask Registers
KSHIFTLW	Shift Left Mask Registers
KSHIFTRB	Shift Right Mask Registers
KSHIFTRD	Shift Right Mask Registers
KSHIFTRQ	Shift Right Mask Registers
KSHIFTRW	Shift Right Mask Registers
KTESTB	T{
Packed Bit Test Masks and Set Flags
T}
KTESTD	T{
Packed Bit Test Masks and Set Flags
T}
KTESTQ	T{
Packed Bit Test Masks and Set Flags
T}
KTESTW	T{
Packed Bit Test Masks and Set Flags
T}
KUNPCKBW	Unpack for Mask Registers
KUNPCKDQ	Unpack for Mask Registers
KUNPCKWD	Unpack for Mask Registers
KXNORB	Bitwise Logical XNOR Masks
KXNORD	Bitwise Logical XNOR Masks
KXNORQ	Bitwise Logical XNOR Masks
KXNORW	Bitwise Logical XNOR Masks
KXORB	Bitwise Logical XOR Masks
KXORD	Bitwise Logical XOR Masks
KXORQ	Bitwise Logical XOR Masks
KXORW	Bitwise Logical XOR Masks
LAHF	T{
Load Status Flags Into AH Register
T}
LAR	Load Access Rights Byte
LDDQU	T{
Load Unaligned Integer 128 Bits
T}
LDMXCSR	Load MXCSR Register
LDS	Load Far Pointer
LDTILECFG	Load Tile Configuration
LEA	Load Effective Address
LEAVE	High Level Procedure Exit
LES	Load Far Pointer
LFENCE	Load Fence
LFS	Load Far Pointer
LGDT	T{
Load Global/Interrupt Descriptor Table Register
T}
LGS	Load Far Pointer
LIDT	T{
Load Global/Interrupt Descriptor Table Register
T}
LLDT	T{
Load Local Descriptor Table Register
T}
LMSW	Load Machine Status Word
LOADIWKEY	T{
Load Internal Wrapping Key With Key Locker
T}
LOCK	Assert LOCK# Signal Prefix
LODS	Load String
LODSB	Load String
LODSD	Load String
LODSQ	Load String
LODSW	Load String
LOOP	Loop According to ECX Counter
LOOPcc	Loop According to ECX Counter
LSL	Load Segment Limit
LSS	Load Far Pointer
LTR	Load Task Register
LZCNT	T{
Count the Number of Leading Zero Bits
T}
MASKMOVDQU	T{
Store Selected Bytes of Double Quadword
T}
MASKMOVQ	T{
Store Selected Bytes of Quadword
T}
MAXPD	T{
Maximum of Packed Double Precision Floating-Point Values
T}
MAXPS	T{
Maximum of Packed Single Precision Floating-Point Values
T}
MAXSD	T{
Return Maximum Scalar Double Precision Floating-Point Value
T}
MAXSS	T{
Return Maximum Scalar Single Precision Floating-Point Value
T}
MFENCE	Memory Fence
MINPD	T{
Minimum of Packed Double Precision Floating-Point Values
T}
MINPS	T{
Minimum of Packed Single Precision Floating-Point Values
T}
MINSD	T{
Return Minimum Scalar Double Precision Floating-Point Value
T}
MINSS	T{
Return Minimum Scalar Single Precision Floating-Point Value
T}
MONITOR	Set Up Monitor Address
MOV	Move
MOV (1)	Move to/from Control Registers
MOV (2)	Move to/from Debug Registers
MOVAPD	T{
Move Aligned Packed Double Precision Floating-Point Values
T}
MOVAPS	T{
Move Aligned Packed Single Precision Floating-Point Values
T}
MOVBE	Move Data After Swapping Bytes
MOVD	Move Doubleword/Move Quadword
MOVDDUP	T{
Replicate Double Precision Floating-Point Values
T}
MOVDIR64B	Move 64 Bytes as Direct Store
MOVDIRI	T{
Move Doubleword as Direct Store
T}
MOVDQ2Q	T{
Move Quadword from XMM to MMX Technology Register
T}
MOVDQA	T{
Move Aligned Packed Integer Values
T}
MOVDQU	T{
Move Unaligned Packed Integer Values
T}
MOVHLPS	T{
Move Packed Single Precision Floating-Point Values High to Low
T}
MOVHPD	T{
Move High Packed Double Precision Floating-Point Value
T}
MOVHPS	T{
Move High Packed Single Precision Floating-Point Values
T}
MOVLHPS	T{
Move Packed Single Precision Floating-Point Values Low to High
T}
MOVLPD	T{
Move Low Packed Double Precision Floating-Point Value
T}
MOVLPS	T{
Move Low Packed Single Precision Floating-Point Values
T}
MOVMSKPD	T{
Extract Packed Double Precision Floating-Point Sign Mask
T}
MOVMSKPS	T{
Extract Packed Single Precision Floating-Point Sign Mask
T}
MOVNTDQ	T{
Store Packed Integers Using Non-Temporal Hint
T}
MOVNTDQA	T{
Load Double Quadword Non-Temporal Aligned Hint
T}
MOVNTI	T{
Store Doubleword Using Non-Temporal Hint
T}
MOVNTPD	T{
Store Packed Double Precision Floating-Point Values Using Non-Temporal Hint
T}
MOVNTPS	T{
Store Packed Single Precision Floating-Point Values Using Non-Temporal Hint
T}
MOVNTQ	T{
Store of Quadword Using Non-Temporal Hint
T}
MOVQ	Move Doubleword/Move Quadword
MOVQ (1)	Move Quadword
MOVQ2DQ	T{
Move Quadword from MMX Technology to XMM Register
T}
MOVS	T{
Move Data From String to String
T}
MOVSB	T{
Move Data From String to String
T}
MOVSD	T{
Move Data From String to String
T}
MOVSD (1)	T{
Move or Merge Scalar Double Precision Floating-Point Value
T}
MOVSHDUP	T{
Replicate Single Precision Floating-Point Values
T}
MOVSLDUP	T{
Replicate Single Precision Floating-Point Values
T}
MOVSQ	T{
Move Data From String to String
T}
MOVSS	T{
Move or Merge Scalar Single Precision Floating-Point Value
T}
MOVSW	T{
Move Data From String to String
T}
MOVSX	Move With Sign-Extension
MOVSXD	Move With Sign-Extension
MOVUPD	T{
Move Unaligned Packed Double Precision Floating-Point Values
T}
MOVUPS	T{
Move Unaligned Packed Single Precision Floating-Point Values
T}
MOVZX	Move With Zero-Extend
MPSADBW	T{
Compute Multiple Packed Sums of Absolute Difference
T}
MUL	Unsigned Multiply
MULPD	T{
Multiply Packed Double Precision Floating-Point Values
T}
MULPS	T{
Multiply Packed Single Precision Floating-Point Values
T}
MULSD	T{
Multiply Scalar Double Precision Floating-Point Value
T}
MULSS	T{
Multiply Scalar Single Precision Floating-Point Values
T}
MULX	T{
Unsigned Multiply Without Affecting Flags
T}
MWAIT	Monitor Wait
NEG	Two's Complement Negation
NOP	No Operation
NOT	One's Complement Negation
OR	Logical Inclusive OR
ORPD	T{
Bitwise Logical OR of Packed Double Precision Floating-Point Values
T}
ORPS	T{
Bitwise Logical OR of Packed Single Precision Floating-Point Values
T}
OUT	Output to Port
OUTS	Output String to Port
OUTSB	Output String to Port
OUTSD	Output String to Port
OUTSW	Output String to Port
PABSB	Packed Absolute Value
PABSD	Packed Absolute Value
PABSQ	Packed Absolute Value
PABSW	Packed Absolute Value
PACKSSDW	Pack With Signed Saturation
PACKSSWB	Pack With Signed Saturation
PACKUSDW	Pack With Unsigned Saturation
PACKUSWB	Pack With Unsigned Saturation
PADDB	Add Packed Integers
PADDD	Add Packed Integers
PADDQ	Add Packed Integers
PADDSB	T{
Add Packed Signed Integers with Signed Saturation
T}
PADDSW	T{
Add Packed Signed Integers with Signed Saturation
T}
PADDUSB	T{
Add Packed Unsigned Integers With Unsigned Saturation
T}
PADDUSW	T{
Add Packed Unsigned Integers With Unsigned Saturation
T}
PADDW	Add Packed Integers
PALIGNR	Packed Align Right
PAND	Logical AND
PANDN	Logical AND NOT
PAUSE	Spin Loop Hint
PAVGB	Average Packed Integers
PAVGW	Average Packed Integers
PBLENDVB	Variable Blend Packed Bytes
PBLENDW	Blend Packed Words
PCLMULQDQ	T{
Carry-Less Multiplication Quadword
T}
PCMPEQB	Compare Packed Data for Equal
PCMPEQD	Compare Packed Data for Equal
PCMPEQQ	T{
Compare Packed Qword Data for Equal
T}
PCMPEQW	Compare Packed Data for Equal
PCMPESTRI	T{
Packed Compare Explicit Length Strings, Return Index
T}
PCMPESTRM	T{
Packed Compare Explicit Length Strings, Return Mask
T}
PCMPGTB	T{
Compare Packed Signed Integers for Greater Than
T}
PCMPGTD	T{
Compare Packed Signed Integers for Greater Than
T}
PCMPGTQ	T{
Compare Packed Data for Greater Than
T}
PCMPGTW	T{
Compare Packed Signed Integers for Greater Than
T}
PCMPISTRI	T{
Packed Compare Implicit Length Strings, Return Index
T}
PCMPISTRM	T{
Packed Compare Implicit Length Strings, Return Mask
T}
PCONFIG	Platform Configuration
PDEP	Parallel Bits Deposit
PEXT	Parallel Bits Extract
PEXTRB	Extract Byte/Dword/Qword
PEXTRD	Extract Byte/Dword/Qword
PEXTRQ	Extract Byte/Dword/Qword
PEXTRW	Extract Word
PHADDD	Packed Horizontal Add
PHADDSW	T{
Packed Horizontal Add and Saturate
T}
PHADDW	Packed Horizontal Add
PHMINPOSUW	Packed Horizontal Word Minimum
PHSUBD	Packed Horizontal Subtract
PHSUBSW	T{
Packed Horizontal Subtract and Saturate
T}
PHSUBW	Packed Horizontal Subtract
PINSRB	Insert Byte/Dword/Qword
PINSRD	Insert Byte/Dword/Qword
PINSRQ	Insert Byte/Dword/Qword
PINSRW	Insert Word
PMADDUBSW	T{
Multiply and Add Packed Signed and Unsigned Bytes
T}
PMADDWD	T{
Multiply and Add Packed Integers
T}
PMAXSB	T{
Maximum of Packed Signed Integers
T}
PMAXSD	T{
Maximum of Packed Signed Integers
T}
PMAXSQ	T{
Maximum of Packed Signed Integers
T}
PMAXSW	T{
Maximum of Packed Signed Integers
T}
PMAXUB	T{
Maximum of Packed Unsigned Integers
T}
PMAXUD	T{
Maximum of Packed Unsigned Integers
T}
PMAXUQ	T{
Maximum of Packed Unsigned Integers
T}
PMAXUW	T{
Maximum of Packed Unsigned Integers
T}
PMINSB	T{
Minimum of Packed Signed Integers
T}
PMINSD	T{
Minimum of Packed Signed Integers
T}
PMINSQ	T{
Minimum of Packed Signed Integers
T}
PMINSW	T{
Minimum of Packed Signed Integers
T}
PMINUB	T{
Minimum of Packed Unsigned Integers
T}
PMINUD	T{
Minimum of Packed Unsigned Integers
T}
PMINUQ	T{
Minimum of Packed Unsigned Integers
T}
PMINUW	T{
Minimum of Packed Unsigned Integers
T}
PMOVMSKB	Move Byte Mask
PMOVSX	Packed Move With Sign Extend
PMOVZX	Packed Move With Zero Extend
PMULDQ	T{
Multiply Packed Doubleword Integers
T}
PMULHRSW	T{
Packed Multiply High With Round and Scale
T}
PMULHUW	T{
Multiply Packed Unsigned Integers and Store High Result
T}
PMULHW	T{
Multiply Packed Signed Integers and Store High Result
T}
PMULLD	T{
Multiply Packed Integers and Store Low Result
T}
PMULLQ	T{
Multiply Packed Integers and Store Low Result
T}
PMULLW	T{
Multiply Packed Signed Integers and Store Low Result
T}
PMULUDQ	T{
Multiply Packed Unsigned Doubleword Integers
T}
POP	Pop a Value From the Stack
POPA	T{
Pop All General-Purpose Registers
T}
POPAD	T{
Pop All General-Purpose Registers
T}
POPCNT	T{
Return the Count of Number of Bits Set to 1
T}
POPF	Pop Stack Into EFLAGS Register
POPFD	Pop Stack Into EFLAGS Register
POPFQ	Pop Stack Into EFLAGS Register
POR	Bitwise Logical OR
PREFETCHW	T{
Prefetch Data Into Caches in Anticipation of a Write
T}
PREFETCHh	Prefetch Data Into Caches
PSADBW	T{
Compute Sum of Absolute Differences
T}
PSHUFB	Packed Shuffle Bytes
PSHUFD	Shuffle Packed Doublewords
PSHUFHW	Shuffle Packed High Words
PSHUFLW	Shuffle Packed Low Words
PSHUFW	Shuffle Packed Words
PSIGNB	Packed SIGN
PSIGND	Packed SIGN
PSIGNW	Packed SIGN
PSLLD	Shift Packed Data Left Logical
PSLLDQ	T{
Shift Double Quadword Left Logical
T}
PSLLQ	Shift Packed Data Left Logical
PSLLW	Shift Packed Data Left Logical
PSRAD	T{
Shift Packed Data Right Arithmetic
T}
PSRAQ	T{
Shift Packed Data Right Arithmetic
T}
PSRAW	T{
Shift Packed Data Right Arithmetic
T}
PSRLD	T{
Shift Packed Data Right Logical
T}
PSRLDQ	T{
Shift Double Quadword Right Logical
T}
PSRLQ	T{
Shift Packed Data Right Logical
T}
PSRLW	T{
Shift Packed Data Right Logical
T}
PSUBB	Subtract Packed Integers
PSUBD	Subtract Packed Integers
PSUBQ	T{
Subtract Packed Quadword Integers
T}
PSUBSB	T{
Subtract Packed Signed Integers With Signed Saturation
T}
PSUBSW	T{
Subtract Packed Signed Integers With Signed Saturation
T}
PSUBUSB	T{
Subtract Packed Unsigned Integers With Unsigned Saturation
T}
PSUBUSW	T{
Subtract Packed Unsigned Integers With Unsigned Saturation
T}
PSUBW	Subtract Packed Integers
PTEST	Logical Compare
PTWRITE	T{
Write Data to a Processor Trace Packet
T}
PUNPCKHBW	Unpack High Data
PUNPCKHDQ	Unpack High Data
PUNPCKHQDQ	Unpack High Data
PUNPCKHWD	Unpack High Data
PUNPCKLBW	Unpack Low Data
PUNPCKLDQ	Unpack Low Data
PUNPCKLQDQ	Unpack Low Data
PUNPCKLWD	Unpack Low Data
PUSH	T{
Push Word, Doubleword, or Quadword Onto the Stack
T}
PUSHA	T{
Push All General-Purpose Registers
T}
PUSHAD	T{
Push All General-Purpose Registers
T}
PUSHF	T{
Push EFLAGS Register Onto the Stack
T}
PUSHFD	T{
Push EFLAGS Register Onto the Stack
T}
PUSHFQ	T{
Push EFLAGS Register Onto the Stack
T}
PXOR	Logical Exclusive OR
RCL	Rotate
RCPPS	T{
Compute Reciprocals of Packed Single Precision Floating-Point Values
T}
RCPSS	T{
Compute Reciprocal of Scalar Single Precision Floating-Point Values
T}
RCR	Rotate
RDFSBASE	Read FS/GS Segment Base
RDGSBASE	Read FS/GS Segment Base
RDMSR	T{
Read From Model Specific Register
T}
RDPID	Read Processor ID
RDPKRU	T{
Read Protection Key Rights for User Pages
T}
RDPMC	T{
Read Performance-Monitoring Counters
T}
RDRAND	Read Random Number
RDSEED	Read Random SEED
RDSSPD	Read Shadow Stack Pointer
RDSSPQ	Read Shadow Stack Pointer
RDTSC	Read Time-Stamp Counter
RDTSCP	T{
Read Time-Stamp Counter and Processor ID
T}
REP	Repeat String Operation Prefix
REPE	Repeat String Operation Prefix
REPNE	Repeat String Operation Prefix
REPNZ	Repeat String Operation Prefix
REPZ	Repeat String Operation Prefix
RET	Return From Procedure
ROL	Rotate
ROR	Rotate
RORX	T{
Rotate Right Logical Without Affecting Flags
T}
ROUNDPD	T{
Round Packed Double Precision Floating-Point Values
T}
ROUNDPS	T{
Round Packed Single Precision Floating-Point Values
T}
ROUNDSD	T{
Round Scalar Double Precision Floating-Point Values
T}
ROUNDSS	T{
Round Scalar Single Precision Floating-Point Values
T}
RSM	T{
Resume From System Management Mode
T}
RSQRTPS	T{
Compute Reciprocals of Square Roots of Packed Single Precision Floating-PointValues
T}
RSQRTSS	T{
Compute Reciprocal of Square Root of Scalar Single Precision Floating-Point Value
T}
RSTORSSP	T{
Restore Saved Shadow Stack Pointer
T}
SAHF	Store AH Into Flags
SAL	Shift
SAR	Shift
SARX	Shift Without Affecting Flags
SAVEPREVSSP	T{
Save Previous Shadow Stack Pointer
T}
SBB	T{
Integer Subtraction With Borrow
T}
SCAS	Scan String
SCASB	Scan String
SCASD	Scan String
SCASW	Scan String
SENDUIPI	T{
Send User Interprocessor Interrupt
T}
SERIALIZE	T{
Serialize Instruction Execution
T}
SETSSBSY	Mark Shadow Stack Busy
SETcc	Set Byte on Condition
SFENCE	Store Fence
SGDT	T{
Store Global Descriptor Table Register
T}
SHA1MSG1	T{
Perform an Intermediate Calculation for the Next Four SHA1 Message Dwords
T}
SHA1MSG2	T{
Perform a Final Calculation for the Next Four SHA1 Message Dwords
T}
SHA1NEXTE	T{
Calculate SHA1 State Variable E After Four Rounds
T}
SHA1RNDS4	T{
Perform Four Rounds of SHA1 Operation
T}
SHA256MSG1	T{
Perform an Intermediate Calculation for the Next Four SHA256 MessageDwords
T}
SHA256MSG2	T{
Perform a Final Calculation for the Next Four SHA256 Message Dwords
T}
SHA256RNDS2	T{
Perform Two Rounds of SHA256 Operation
T}
SHL	Shift
SHLD	Double Precision Shift Left
SHLX	Shift Without Affecting Flags
SHR	Shift
SHRD	Double Precision Shift Right
SHRX	Shift Without Affecting Flags
SHUFPD	T{
Packed Interleave Shuffle of Pairs of Double Precision Floating-Point Values
T}
SHUFPS	T{
Packed Interleave Shuffle of Quadruplets of Single Precision Floating-Point Values
T}
SIDT	T{
Store Interrupt Descriptor Table Register
T}
SLDT	T{
Store Local Descriptor Table Register
T}
SMSW	Store Machine Status Word
SQRTPD	T{
Square Root of Double Precision Floating-Point Values
T}
SQRTPS	T{
Square Root of Single Precision Floating-Point Values
T}
SQRTSD	T{
Compute Square Root of Scalar Double Precision Floating-Point Value
T}
SQRTSS	T{
Compute Square Root of Scalar Single Precision Value
T}
STAC	Set AC Flag in EFLAGS Register
STC	Set Carry Flag
STD	Set Direction Flag
STI	Set Interrupt Flag
STMXCSR	Store MXCSR Register State
STOS	Store String
STOSB	Store String
STOSD	Store String
STOSQ	Store String
STOSW	Store String
STR	Store Task Register
STTILECFG	Store Tile Configuration
STUI	Set User Interrupt Flag
SUB	Subtract
SUBPD	T{
Subtract Packed Double Precision Floating-Point Values
T}
SUBPS	T{
Subtract Packed Single Precision Floating-Point Values
T}
SUBSD	T{
Subtract Scalar Double Precision Floating-Point Value
T}
SUBSS	T{
Subtract Scalar Single Precision Floating-Point Value
T}
SWAPGS	Swap GS Base Register
SYSCALL	Fast System Call
SYSENTER	Fast System Call
SYSEXIT	T{
Fast Return from Fast System Call
T}
SYSRET	Return From Fast System Call
TDPBF16PS	T{
Dot Product of BF16 Tiles Accumulated into Packed Single Precision Tile
T}
TDPBSSD	T{
Dot Product of Signed/Unsigned Bytes with DwordAccumulation
T}
TDPBSUD	T{
Dot Product of Signed/Unsigned Bytes with DwordAccumulation
T}
TDPBUSD	T{
Dot Product of Signed/Unsigned Bytes with DwordAccumulation
T}
TDPBUUD	T{
Dot Product of Signed/Unsigned Bytes with DwordAccumulation
T}
TEST	Logical Compare
TESTUI	Determine User Interrupt Flag
TILELOADD	Load Tile
TILELOADDT1	Load Tile
TILERELEASE	Release Tile
TILESTORED	Store Tile
TILEZERO	Zero Tile
TPAUSE	Timed PAUSE
TZCNT	T{
Count the Number of Trailing Zero Bits
T}
UCOMISD	T{
Unordered Compare Scalar Double Precision Floating-Point Values and Set EFLAGS
T}
UCOMISS	T{
Unordered Compare Scalar Single Precision Floating-Point Values and Set EFLAGS
T}
UD	Undefined Instruction
UIRET	User-Interrupt Return
UMONITOR	T{
User Level Set Up Monitor Address
T}
UMWAIT	User Level Monitor Wait
UNPCKHPD	T{
Unpack and Interleave High Packed Double Precision Floating-Point Values
T}
UNPCKHPS	T{
Unpack and Interleave High Packed Single Precision Floating-Point Values
T}
UNPCKLPD	T{
Unpack and Interleave Low Packed Double Precision Floating-Point Values
T}
UNPCKLPS	T{
Unpack and Interleave Low Packed Single Precision Floating-Point Values
T}
VADDPH	Add Packed FP16 Values
VADDSH	Add Scalar FP16 Values
VALIGND	T{
Align Doubleword/Quadword Vectors
T}
VALIGNQ	T{
Align Doubleword/Quadword Vectors
T}
VBLENDMPD	T{
Blend Float64/Float32 Vectors Using an OpMask Control
T}
VBLENDMPS	T{
Blend Float64/Float32 Vectors Using an OpMask Control
T}
VBROADCAST	T{
Load with Broadcast Floating-Point Data
T}
VCMPPH	Compare Packed FP16 Values
VCMPSH	Compare Scalar FP16 Values
VCOMISH	T{
Compare Scalar Ordered FP16 Values and Set EFLAGS
T}
VCOMPRESSPD	T{
Store Sparse Packed Double Precision Floating-Point Values Into DenseMemory
T}
VCOMPRESSPS	T{
Store Sparse Packed Single Precision Floating-Point Values Into Dense Memory
T}
VCOMPRESSW	T{
Store Sparse Packed Byte/Word Integer Values Into DenseMemory/Register
T}
VCVTDQ2PH	T{
Convert Packed Signed Doubleword Integers to Packed FP16 Values
T}
VCVTNE2PS2BF16	T{
Convert Two Packed Single Data to One Packed BF16 Data
T}
VCVTNEPS2BF16	T{
Convert Packed Single Data to Packed BF16 Data
T}
VCVTPD2PH	T{
Convert Packed Double Precision FP Values to Packed FP16 Values
T}
VCVTPD2QQ	T{
Convert Packed Double Precision Floating-Point Values to Packed QuadwordIntegers
T}
VCVTPD2UDQ	T{
Convert Packed Double Precision Floating-Point Values to Packed UnsignedDoubleword Integers
T}
VCVTPD2UQQ	T{
Convert Packed Double Precision Floating-Point Values to Packed UnsignedQuadword Integers
T}
VCVTPH2DQ	T{
Convert Packed FP16 Values to Signed Doubleword Integers
T}
VCVTPH2PD	T{
Convert Packed FP16 Values to FP64 Values
T}
VCVTPH2PS	T{
Convert Packed FP16 Values to Single Precision Floating-PointValues
T}
VCVTPH2PSX	T{
Convert Packed FP16 Values to Single Precision Floating-PointValues
T}
VCVTPH2QQ	T{
Convert Packed FP16 Values to Signed Quadword Integer Values
T}
VCVTPH2UDQ	T{
Convert Packed FP16 Values to Unsigned Doubleword Integers
T}
VCVTPH2UQQ	T{
Convert Packed FP16 Values to Unsigned Quadword Integers
T}
VCVTPH2UW	T{
Convert Packed FP16 Values to Unsigned Word Integers
T}
VCVTPH2W	T{
Convert Packed FP16 Values to Signed Word Integers
T}
VCVTPS2PH	T{
Convert Single-Precision FP Value to 16-bit FP Value
T}
VCVTPS2PHX	T{
Convert Packed Single Precision Floating-Point Values to Packed FP16 Values
T}
VCVTPS2QQ	T{
Convert Packed Single Precision Floating-Point Values to Packed SignedQuadword Integer Values
T}
VCVTPS2UDQ	T{
Convert Packed Single Precision Floating-Point Values to Packed UnsignedDoubleword Integer Values
T}
VCVTPS2UQQ	T{
Convert Packed Single Precision Floating-Point Values to Packed UnsignedQuadword Integer Values
T}
VCVTQQ2PD	T{
Convert Packed Quadword Integers to Packed Double Precision Floating-PointValues
T}
VCVTQQ2PH	T{
Convert Packed Signed Quadword Integers to Packed FP16 Values
T}
VCVTQQ2PS	T{
Convert Packed Quadword Integers to Packed Single Precision Floating-PointValues
T}
VCVTSD2SH	T{
Convert Low FP64 Value to an FP16 Value
T}
VCVTSD2USI	T{
Convert Scalar Double Precision Floating-Point Value to Unsigned DoublewordInteger
T}
VCVTSH2SD	T{
Convert Low FP16 Value to an FP64 Value
T}
VCVTSH2SI	T{
Convert Low FP16 Value to Signed Integer
T}
VCVTSH2SS	T{
Convert Low FP16 Value to FP32 Value
T}
VCVTSH2USI	T{
Convert Low FP16 Value to Unsigned Integer
T}
VCVTSI2SH	T{
Convert a Signed Doubleword/Quadword Integer to an FP16 Value
T}
VCVTSS2SH	T{
Convert Low FP32 Value to an FP16 Value
T}
VCVTSS2USI	T{
Convert Scalar Single Precision Floating-Point Value to Unsigned DoublewordInteger
T}
VCVTTPD2QQ	T{
Convert With Truncation Packed Double Precision Floating-Point Values toPacked Quadword Integers
T}
VCVTTPD2UDQ	T{
Convert With Truncation Packed Double Precision Floating-Point Values toPacked Unsigned Doubleword Integers
T}
VCVTTPD2UQQ	T{
Convert With Truncation Packed Double Precision Floating-Point Values toPacked Unsigned Quadword Integers
T}
VCVTTPH2DQ	T{
Convert with Truncation Packed FP16 Values to Signed Doubleword Integers
T}
VCVTTPH2QQ	T{
Convert with Truncation Packed FP16 Values to Signed Quadword Integers
T}
VCVTTPH2UDQ	T{
Convert with Truncation Packed FP16 Values to Unsigned DoublewordIntegers
T}
VCVTTPH2UQQ	T{
Convert with Truncation Packed FP16 Values to Unsigned Quadword Integers
T}
VCVTTPH2UW	T{
Convert Packed FP16 Values to Unsigned Word Integers
T}
VCVTTPH2W	T{
Convert Packed FP16 Values to Signed Word Integers
T}
VCVTTPS2QQ	T{
Convert With Truncation Packed Single Precision Floating-Point Values toPacked Signed Quadword Integer Values
T}
VCVTTPS2UDQ	T{
Convert With Truncation Packed Single Precision Floating-Point Values toPacked Unsigned Doubleword Integer Values
T}
VCVTTPS2UQQ	T{
Convert With Truncation Packed Single Precision Floating-Point Values toPacked Unsigned Quadword Integer Values
T}
VCVTTSD2USI	T{
Convert With Truncation Scalar Double Precision Floating-Point Value toUnsigned Integer
T}
VCVTTSH2SI	T{
Convert with Truncation Low FP16 Value to a Signed Integer
T}
VCVTTSH2USI	T{
Convert with Truncation Low FP16 Value to an Unsigned Integer
T}
VCVTTSS2USI	T{
Convert With Truncation Scalar Single Precision Floating-Point Value toUnsigned Integer
T}
VCVTUDQ2PD	T{
Convert Packed Unsigned Doubleword Integers to Packed Double PrecisionFloating-Point Values
T}
VCVTUDQ2PH	T{
Convert Packed Unsigned Doubleword Integers to Packed FP16 Values
T}
VCVTUDQ2PS	T{
Convert Packed Unsigned Doubleword Integers to Packed Single PrecisionFloating-Point Values
T}
VCVTUQQ2PD	T{
Convert Packed Unsigned Quadword Integers to Packed Double PrecisionFloating-Point Values
T}
VCVTUQQ2PH	T{
Convert Packed Unsigned Quadword Integers to Packed FP16 Values
T}
VCVTUQQ2PS	T{
Convert Packed Unsigned Quadword Integers to Packed Single PrecisionFloating-Point Values
T}
VCVTUSI2SD	T{
Convert Unsigned Integer to Scalar Double Precision Floating-Point Value
T}
VCVTUSI2SH	T{
Convert Unsigned Doubleword Integer to an FP16 Value
T}
VCVTUSI2SS	T{
Convert Unsigned Integer to Scalar Single Precision Floating-Point Value
T}
VCVTUW2PH	T{
Convert Packed Unsigned Word Integers to FP16 Values
T}
VCVTW2PH	T{
Convert Packed Signed Word Integers to FP16 Values
T}
VDBPSADBW	T{
Double Block Packed Sum-Absolute-Differences (SAD) on Unsigned Bytes
T}
VDIVPH	Divide Packed FP16 Values
VDIVSH	Divide Scalar FP16 Values
VDPBF16PS	T{
Dot Product of BF16 Pairs Accumulated Into Packed Single Precision
T}
VERR	T{
Verify a Segment for Reading or Writing
T}
VERW	T{
Verify a Segment for Reading or Writing
T}
VEXPANDPD	T{
Load Sparse Packed Double Precision Floating-Point Values From Dense Memory
T}
VEXPANDPS	T{
Load Sparse Packed Single Precision Floating-Point Values From Dense Memory
T}
VEXTRACTF128	T{
Extract Packed Floating-Point Values
T}
VEXTRACTF32x4	T{
Extract Packed Floating-Point Values
T}
VEXTRACTF32x8	T{
Extract Packed Floating-Point Values
T}
VEXTRACTF64x2	T{
Extract Packed Floating-Point Values
T}
VEXTRACTF64x4	T{
Extract Packed Floating-Point Values
T}
VEXTRACTI128	ExtractPacked Integer Values
VEXTRACTI32x4	ExtractPacked Integer Values
VEXTRACTI32x8	ExtractPacked Integer Values
VEXTRACTI64x2	ExtractPacked Integer Values
VEXTRACTI64x4	ExtractPacked Integer Values
VFCMADDCPH	T{
Complex Multiply and Accumulate FP16 Values
T}
VFCMADDCSH	T{
Complex Multiply and Accumulate Scalar FP16 Values
T}
VFCMULCPH	Complex Multiply FP16 Values
VFCMULCSH	T{
Complex Multiply Scalar FP16 Values
T}
VFIXUPIMMPD	T{
Fix Up Special Packed Float64 Values
T}
VFIXUPIMMPS	T{
Fix Up Special Packed Float32 Values
T}
VFIXUPIMMSD	T{
Fix Up Special Scalar Float64 Value
T}
VFIXUPIMMSS	T{
Fix Up Special Scalar Float32 Value
T}
VFMADD132PD	T{
Fused Multiply-Add of Packed DoublePrecision Floating-Point Values
T}
VFMADD132PH	T{
Fused Multiply-Add of Packed FP16 Values
T}
VFMADD132PS	T{
Fused Multiply-Add of Packed SinglePrecision Floating-Point Values
T}
VFMADD132SD	T{
Fused Multiply-Add of Scalar DoublePrecision Floating-Point Values
T}
VFMADD132SH	T{
Fused Multiply-Add of Scalar FP16 Values
T}
VFMADD132SS	T{
Fused Multiply-Add of Scalar Single PrecisionFloating-Point Values
T}
VFMADD213PD	T{
Fused Multiply-Add of Packed DoublePrecision Floating-Point Values
T}
VFMADD213PH	T{
Fused Multiply-Add of Packed FP16 Values
T}
VFMADD213PS	T{
Fused Multiply-Add of Packed SinglePrecision Floating-Point Values
T}
VFMADD213SD	T{
Fused Multiply-Add of Scalar DoublePrecision Floating-Point Values
T}
VFMADD213SH	T{
Fused Multiply-Add of Scalar FP16 Values
T}
VFMADD213SS	T{
Fused Multiply-Add of Scalar Single PrecisionFloating-Point Values
T}
VFMADD231PD	T{
Fused Multiply-Add of Packed DoublePrecision Floating-Point Values
T}
VFMADD231PH	T{
Fused Multiply-Add of Packed FP16 Values
T}
VFMADD231PS	T{
Fused Multiply-Add of Packed SinglePrecision Floating-Point Values
T}
VFMADD231SD	T{
Fused Multiply-Add of Scalar DoublePrecision Floating-Point Values
T}
VFMADD231SH	T{
Fused Multiply-Add of Scalar FP16 Values
T}
VFMADD231SS	T{
Fused Multiply-Add of Scalar Single PrecisionFloating-Point Values
T}
VFMADDCPH	T{
Complex Multiply and Accumulate FP16 Values
T}
VFMADDCSH	T{
Complex Multiply and Accumulate Scalar FP16 Values
T}
VFMADDRND231PD	T{
Fused Multiply-Add of Packed Double-Precision Floating-Point Valueswith rounding control
T}
VFMADDSUB132PD	T{
Fused Multiply-AlternatingAdd/Subtract of Packed Double Precision Floating-Point Values
T}
VFMADDSUB132PH	T{
Fused Multiply-AlternatingAdd/Subtract of Packed FP16 Values
T}
VFMADDSUB132PS	T{
Fused Multiply-AlternatingAdd/Subtract of Packed Single Precision Floating-Point Values
T}
VFMADDSUB213PD	T{
Fused Multiply-AlternatingAdd/Subtract of Packed Double Precision Floating-Point Values
T}
VFMADDSUB213PH	T{
Fused Multiply-AlternatingAdd/Subtract of Packed FP16 Values
T}
VFMADDSUB213PS	T{
Fused Multiply-AlternatingAdd/Subtract of Packed Single Precision Floating-Point Values
T}
VFMADDSUB231PD	T{
Fused Multiply-AlternatingAdd/Subtract of Packed Double Precision Floating-Point Values
T}
VFMADDSUB231PH	T{
Fused Multiply-AlternatingAdd/Subtract of Packed FP16 Values
T}
VFMADDSUB231PS	T{
Fused Multiply-AlternatingAdd/Subtract of Packed Single Precision Floating-Point Values
T}
VFMSUB132PD	T{
Fused Multiply-Subtract of Packed DoublePrecision Floating-Point Values
T}
VFMSUB132PH	T{
Fused Multiply-Subtract of Packed FP16 Values
T}
VFMSUB132PS	T{
Fused Multiply-Subtract of Packed SinglePrecision Floating-Point Values
T}
VFMSUB132SD	T{
Fused Multiply-Subtract of Scalar DoublePrecision Floating-Point Values
T}
VFMSUB132SH	T{
Fused Multiply-Subtract of Scalar FP16 Values
T}
VFMSUB132SS	T{
Fused Multiply-Subtract of Scalar SinglePrecision Floating-Point Values
T}
VFMSUB213PD	T{
Fused Multiply-Subtract of Packed DoublePrecision Floating-Point Values
T}
VFMSUB213PH	T{
Fused Multiply-Subtract of Packed FP16 Values
T}
VFMSUB213PS	T{
Fused Multiply-Subtract of Packed SinglePrecision Floating-Point Values
T}
VFMSUB213SD	T{
Fused Multiply-Subtract of Scalar DoublePrecision Floating-Point Values
T}
VFMSUB213SH	T{
Fused Multiply-Subtract of Scalar FP16 Values
T}
VFMSUB213SS	T{
Fused Multiply-Subtract of Scalar SinglePrecision Floating-Point Values
T}
VFMSUB231PD	T{
Fused Multiply-Subtract of Packed DoublePrecision Floating-Point Values
T}
VFMSUB231PH	T{
Fused Multiply-Subtract of Packed FP16 Values
T}
VFMSUB231PS	T{
Fused Multiply-Subtract of Packed SinglePrecision Floating-Point Values
T}
VFMSUB231SD	T{
Fused Multiply-Subtract of Scalar DoublePrecision Floating-Point Values
T}
VFMSUB231SH	T{
Fused Multiply-Subtract of Scalar FP16 Values
T}
VFMSUB231SS	T{
Fused Multiply-Subtract of Scalar SinglePrecision Floating-Point Values
T}
VFMSUBADD132PD	T{
Fused Multiply-AlternatingSubtract/Add of Packed Double Precision Floating-Point Values
T}
VFMSUBADD132PH	T{
Fused Multiply-AlternatingSubtract/Add of Packed FP16 Values
T}
VFMSUBADD132PS	T{
Fused Multiply-AlternatingSubtract/Add of Packed Single Precision Floating-Point Values
T}
VFMSUBADD213PD	T{
Fused Multiply-AlternatingSubtract/Add of Packed Double Precision Floating-Point Values
T}
VFMSUBADD213PH	T{
Fused Multiply-AlternatingSubtract/Add of Packed FP16 Values
T}
VFMSUBADD213PS	T{
Fused Multiply-AlternatingSubtract/Add of Packed Single Precision Floating-Point Values
T}
VFMSUBADD231PD	T{
Fused Multiply-AlternatingSubtract/Add of Packed Double Precision Floating-Point Values
T}
VFMSUBADD231PH	T{
Fused Multiply-AlternatingSubtract/Add of Packed FP16 Values
T}
VFMSUBADD231PS	T{
Fused Multiply-AlternatingSubtract/Add of Packed Single Precision Floating-Point Values
T}
VFMULCPH	Complex Multiply FP16 Values
VFMULCSH	T{
Complex Multiply Scalar FP16 Values
T}
VFNMADD132PD	T{
Fused Negative Multiply-Add of PackedDouble Precision Floating-Point Values
T}
VFNMADD132PH	T{
Fused Multiply-Add of Packed FP16 Values
T}
VFNMADD132PS	T{
Fused Negative Multiply-Add of PackedSingle Precision Floating-Point Values
T}
VFNMADD132SD	T{
Fused Negative Multiply-Add of ScalarDouble Precision Floating-Point Values
T}
VFNMADD132SH	T{
Fused Multiply-Add of Scalar FP16 Values
T}
VFNMADD132SS	T{
Fused Negative Multiply-Add of ScalarSingle Precision Floating-Point Values
T}
VFNMADD213PD	T{
Fused Negative Multiply-Add of PackedDouble Precision Floating-Point Values
T}
VFNMADD213PH	T{
Fused Multiply-Add of Packed FP16 Values
T}
VFNMADD213PS	T{
Fused Negative Multiply-Add of PackedSingle Precision Floating-Point Values
T}
VFNMADD213SD	T{
Fused Negative Multiply-Add of ScalarDouble Precision Floating-Point Values
T}
VFNMADD213SH	T{
Fused Multiply-Add of Scalar FP16 Values
T}
VFNMADD213SS	T{
Fused Negative Multiply-Add of ScalarSingle Precision Floating-Point Values
T}
VFNMADD231PD	T{
Fused Negative Multiply-Add of PackedDouble Precision Floating-Point Values
T}
VFNMADD231PH	T{
Fused Multiply-Add of Packed FP16 Values
T}
VFNMADD231PS	T{
Fused Negative Multiply-Add of PackedSingle Precision Floating-Point Values
T}
VFNMADD231SD	T{
Fused Negative Multiply-Add of ScalarDouble Precision Floating-Point Values
T}
VFNMADD231SH	T{
Fused Multiply-Add of Scalar FP16 Values
T}
VFNMADD231SS	T{
Fused Negative Multiply-Add of ScalarSingle Precision Floating-Point Values
T}
VFNMSUB132PD	T{
Fused Negative Multiply-Subtract ofPacked Double Precision Floating-Point Values
T}
VFNMSUB132PH	T{
Fused Multiply-Subtract of Packed FP16 Values
T}
VFNMSUB132PS	T{
Fused Negative Multiply-Subtract ofPacked Single Precision Floating-Point Values
T}
VFNMSUB132SD	T{
Fused Negative Multiply-Subtract ofScalar Double Precision Floating-Point Values
T}
VFNMSUB132SH	T{
Fused Multiply-Subtract of Scalar FP16 Values
T}
VFNMSUB132SS	T{
Fused Negative Multiply-Subtract ofScalar Single Precision Floating-Point Values
T}
VFNMSUB213PD	T{
Fused Negative Multiply-Subtract ofPacked Double Precision Floating-Point Values
T}
VFNMSUB213PH	T{
Fused Multiply-Subtract of Packed FP16 Values
T}
VFNMSUB213PS	T{
Fused Negative Multiply-Subtract ofPacked Single Precision Floating-Point Values
T}
VFNMSUB213SD	T{
Fused Negative Multiply-Subtract ofScalar Double Precision Floating-Point Values
T}
VFNMSUB213SH	T{
Fused Multiply-Subtract of Scalar FP16 Values
T}
VFNMSUB213SS	T{
Fused Negative Multiply-Subtract ofScalar Single Precision Floating-Point Values
T}
VFNMSUB231PD	T{
Fused Negative Multiply-Subtract ofPacked Double Precision Floating-Point Values
T}
VFNMSUB231PH	T{
Fused Multiply-Subtract of Packed FP16 Values
T}
VFNMSUB231PS	T{
Fused Negative Multiply-Subtract ofPacked Single Precision Floating-Point Values
T}
VFNMSUB231SD	T{
Fused Negative Multiply-Subtract ofScalar Double Precision Floating-Point Values
T}
VFNMSUB231SH	T{
Fused Multiply-Subtract of Scalar FP16 Values
T}
VFNMSUB231SS	T{
Fused Negative Multiply-Subtract ofScalar Single Precision Floating-Point Values
T}
VFPCLASSPD	T{
Tests Types of Packed Float64 Values
T}
VFPCLASSPH	T{
Test Types of Packed FP16 Values
T}
VFPCLASSPS	T{
Tests Types of Packed Float32 Values
T}
VFPCLASSSD	T{
Tests Type of a Scalar Float64 Value
T}
VFPCLASSSH	T{
Test Types of Scalar FP16 Values
T}
VFPCLASSSS	T{
Tests Type of a Scalar Float32 Value
T}
VGATHERDPD	T{
Gather Packed Double Precision Floating-Point Values UsingSigned Dword/Qword Indices
T}
VGATHERDPD (1)	T{
Gather Packed Single, Packed Double with Signed Dword Indices
T}
VGATHERDPS	T{
Gather Packed Single Precision Floating-Point Values UsingSigned Dword/Qword Indices
T}
VGATHERDPS (1)	T{
Gather Packed Single, Packed Double with Signed Dword Indices
T}
VGATHERQPD	T{
Gather Packed Double Precision Floating-Point Values UsingSigned Dword/Qword Indices
T}
VGATHERQPD (1)	T{
Gather Packed Single, Packed Double with Signed Qword Indices
T}
VGATHERQPS	T{
Gather Packed Single Precision Floating-Point Values UsingSigned Dword/Qword Indices
T}
VGATHERQPS (1)	T{
Gather Packed Single, Packed Double with Signed Qword Indices
T}
VGETEXPPD	T{
Convert Exponents of Packed Double Precision Floating-Point Values to DoublePrecision Floating-Point Values
T}
VGETEXPPH	T{
Convert Exponents of Packed FP16 Values to FP16 Values
T}
VGETEXPPS	T{
Convert Exponents of Packed Single Precision Floating-Point Values to SinglePrecision Floating-Point Values
T}
VGETEXPSD	T{
Convert Exponents of Scalar Double Precision Floating-Point Value to DoublePrecision Floating-Point Value
T}
VGETEXPSH	T{
Convert Exponents of Scalar FP16 Values to FP16 Values
T}
VGETEXPSS	T{
Convert Exponents of Scalar Single Precision Floating-Point Value to SinglePrecision Floating-Point Value
T}
VGETMANTPD	T{
Extract Float64 Vector of Normalized Mantissas From Float64 Vector
T}
VGETMANTPH	T{
Extract FP16 Vector of Normalized Mantissas from FP16 Vector
T}
VGETMANTPS	T{
Extract Float32 Vector of Normalized Mantissas From Float32 Vector
T}
VGETMANTSD	T{
Extract Float64 of Normalized Mantissa From Float64 Scalar
T}
VGETMANTSH	T{
Extract FP16 of Normalized Mantissa from FP16 Scalar
T}
VGETMANTSS	T{
Extract Float32 Vector of Normalized Mantissa From Float32 Scalar
T}
VINSERTF128	T{
Insert PackedFloating-Point Values
T}
VINSERTF32x4	T{
Insert PackedFloating-Point Values
T}
VINSERTF32x8	T{
Insert PackedFloating-Point Values
T}
VINSERTF64x2	T{
Insert PackedFloating-Point Values
T}
VINSERTF64x4	T{
Insert PackedFloating-Point Values
T}
VINSERTI128	Insert PackedInteger Values
VINSERTI32x4	Insert PackedInteger Values
VINSERTI32x8	Insert PackedInteger Values
VINSERTI64x2	Insert PackedInteger Values
VINSERTI64x4	Insert PackedInteger Values
VMASKMOV	T{
Conditional SIMD Packed Loads and Stores
T}
VMAXPH	T{
Return Maximum of Packed FP16 Values
T}
VMAXSH	T{
Return Maximum of Scalar FP16 Values
T}
VMINPH	T{
Return Minimum of Packed FP16 Values
T}
VMINSH	T{
Return Minimum Scalar FP16 Value
T}
VMOVDQA32	T{
Move Aligned Packed Integer Values
T}
VMOVDQA64	T{
Move Aligned Packed Integer Values
T}
VMOVDQU16	T{
Move Unaligned Packed Integer Values
T}
VMOVDQU32	T{
Move Unaligned Packed Integer Values
T}
VMOVDQU64	T{
Move Unaligned Packed Integer Values
T}
VMOVDQU8	T{
Move Unaligned Packed Integer Values
T}
VMOVSH	Move Scalar FP16 Value
VMOVW	Move Word
VMULPH	Multiply Packed FP16 Values
VMULSH	Multiply Scalar FP16 Values
VP2INTERSECTD	T{
Compute Intersection Between DWORDS/QUADWORDS to aPair of Mask Registers
T}
VP2INTERSECTQ	T{
Compute Intersection Between DWORDS/QUADWORDS to aPair of Mask Registers
T}
VPBLENDD	Blend Packed Dwords
VPBLENDMB	T{
Blend Byte/Word Vectors Using an Opmask Control
T}
VPBLENDMD	T{
Blend Int32/Int64 Vectors Using an OpMask Control
T}
VPBLENDMQ	T{
Blend Int32/Int64 Vectors Using an OpMask Control
T}
VPBLENDMW	T{
Blend Byte/Word Vectors Using an Opmask Control
T}
VPBROADCAST	Load Integer and Broadcast
VPBROADCASTB	T{
Load With Broadcast Integer Data From General Purpose Register
T}
VPBROADCASTD	T{
Load With Broadcast Integer Data From General Purpose Register
T}
VPBROADCASTM	T{
Broadcast Mask to Vector Register
T}
VPBROADCASTQ	T{
Load With Broadcast Integer Data From General Purpose Register
T}
VPBROADCASTW	T{
Load With Broadcast Integer Data From General Purpose Register
T}
VPCMPB	T{
Compare Packed Byte Values Into Mask
T}
VPCMPD	T{
Compare Packed Integer Values Into Mask
T}
VPCMPQ	T{
Compare Packed Integer Values Into Mask
T}
VPCMPUB	T{
Compare Packed Byte Values Into Mask
T}
VPCMPUD	T{
Compare Packed Integer Values Into Mask
T}
VPCMPUQ	T{
Compare Packed Integer Values Into Mask
T}
VPCMPUW	T{
Compare Packed Word Values Into Mask
T}
VPCMPW	T{
Compare Packed Word Values Into Mask
T}
VPCOMPRESSB	T{
Store Sparse Packed Byte/Word Integer Values Into DenseMemory/Register
T}
VPCOMPRESSD	T{
Store Sparse Packed Doubleword Integer Values Into Dense Memory/Register
T}
VPCOMPRESSQ	T{
Store Sparse Packed Quadword Integer Values Into Dense Memory/Register
T}
VPCONFLICTD	T{
Detect Conflicts Within a Vector of Packed Dword/Qword Values Into DenseMemory/ Register
T}
VPCONFLICTQ	T{
Detect Conflicts Within a Vector of Packed Dword/Qword Values Into DenseMemory/ Register
T}
VPDPBUSD	T{
Multiply and Add Unsigned and Signed Bytes
T}
VPDPBUSDS	T{
Multiply and Add Unsigned and Signed Bytes With Saturation
T}
VPDPWSSD	T{
Multiply and Add Signed Word Integers
T}
VPDPWSSDS	T{
Multiply and Add Signed Word Integers With Saturation
T}
VPERM2F128	Permute Floating-Point Values
VPERM2I128	Permute Integer Values
VPERMB	Permute Packed Bytes Elements
VPERMD	T{
Permute Packed Doubleword/Word Elements
T}
VPERMI2B	T{
Full Permute of Bytes From Two Tables Overwriting the Index
T}
VPERMI2D	T{
Full Permute From Two Tables Overwriting the Index
T}
VPERMI2PD	T{
Full Permute From Two Tables Overwriting the Index
T}
VPERMI2PS	T{
Full Permute From Two Tables Overwriting the Index
T}
VPERMI2Q	T{
Full Permute From Two Tables Overwriting the Index
T}
VPERMI2W	T{
Full Permute From Two Tables Overwriting the Index
T}
VPERMILPD	T{
Permute In-Lane of Pairs of Double Precision Floating-Point Values
T}
VPERMILPS	T{
Permute In-Lane of Quadruples of Single Precision Floating-Point Values
T}
VPERMPD	T{
Permute Double Precision Floating-Point Elements
T}
VPERMPS	T{
Permute Single Precision Floating-Point Elements
T}
VPERMQ	Qwords Element Permutation
VPERMT2B	T{
Full Permute of Bytes From Two Tables Overwriting a Table
T}
VPERMT2D	T{
Full Permute From Two Tables Overwriting One Table
T}
VPERMT2PD	T{
Full Permute From Two Tables Overwriting One Table
T}
VPERMT2PS	T{
Full Permute From Two Tables Overwriting One Table
T}
VPERMT2Q	T{
Full Permute From Two Tables Overwriting One Table
T}
VPERMT2W	T{
Full Permute From Two Tables Overwriting One Table
T}
VPERMW	T{
Permute Packed Doubleword/Word Elements
T}
VPEXPANDB	Expand Byte/Word Values
VPEXPANDD	T{
Load Sparse Packed Doubleword Integer Values From Dense Memory/Register
T}
VPEXPANDQ	T{
Load Sparse Packed Quadword Integer Values From Dense Memory/Register
T}
VPEXPANDW	Expand Byte/Word Values
VPGATHERDD	T{
Gather Packed Dword Values Using Signed Dword/Qword Indices
T}
VPGATHERDD (1)	T{
Gather Packed Dword, Packed Qword With Signed Dword Indices
T}
VPGATHERDQ	T{
Gather Packed Dword, Packed Qword With Signed Dword Indices
T}
VPGATHERDQ (1)	T{
Gather Packed Qword Values Using Signed Dword/Qword Indices
T}
VPGATHERQD	T{
Gather Packed Dword Values Using Signed Dword/Qword Indices
T}
VPGATHERQD (1)	T{
Gather Packed Dword, Packed Qword with Signed Qword Indices
T}
VPGATHERQQ	T{
Gather Packed Qword Values Using Signed Dword/Qword Indices
T}
VPGATHERQQ (1)	T{
Gather Packed Dword, Packed Qword with Signed Qword Indices
T}
VPLZCNTD	T{
Count the Number of Leading Zero Bits for Packed Dword, Packed Qword Values
T}
VPLZCNTQ	T{
Count the Number of Leading Zero Bits for Packed Dword, Packed Qword Values
T}
VPMADD52HUQ	T{
Packed Multiply of Unsigned 52-Bit Unsigned Integers and Add High 52-BitProducts to 64-Bit Accumulators
T}
VPMADD52LUQ	T{
Packed Multiply of Unsigned 52-Bit Integers and Add the Low 52-Bit Productsto Qword Accumulators
T}
VPMASKMOV	T{
Conditional SIMD Integer Packed Loads and Stores
T}
VPMOVB2M	T{
Convert a Vector Register to a Mask
T}
VPMOVD2M	T{
Convert a Vector Register to a Mask
T}
VPMOVDB	Down Convert DWord to Byte
VPMOVDW	Down Convert DWord to Word
VPMOVM2B	T{
Convert a Mask Register to a VectorRegister
T}
VPMOVM2D	T{
Convert a Mask Register to a VectorRegister
T}
VPMOVM2Q	T{
Convert a Mask Register to a VectorRegister
T}
VPMOVM2W	T{
Convert a Mask Register to a VectorRegister
T}
VPMOVQ2M	T{
Convert a Vector Register to a Mask
T}
VPMOVQB	Down Convert QWord to Byte
VPMOVQD	Down Convert QWord to DWord
VPMOVQW	Down Convert QWord to Word
VPMOVSDB	Down Convert DWord to Byte
VPMOVSDW	Down Convert DWord to Word
VPMOVSQB	Down Convert QWord to Byte
VPMOVSQD	Down Convert QWord to DWord
VPMOVSQW	Down Convert QWord to Word
VPMOVSWB	Down Convert Word to Byte
VPMOVUSDB	Down Convert DWord to Byte
VPMOVUSDW	Down Convert DWord to Word
VPMOVUSQB	Down Convert QWord to Byte
VPMOVUSQD	Down Convert QWord to DWord
VPMOVUSQW	Down Convert QWord to Word
VPMOVUSWB	Down Convert Word to Byte
VPMOVW2M	T{
Convert a Vector Register to a Mask
T}
VPMOVWB	Down Convert Word to Byte
VPMULTISHIFTQB	T{
Select Packed Unaligned Bytes From Quadword Sources
T}
VPOPCNT	T{
Return the Count of Number of Bits Set to 1 in BYTE/WORD/DWORD/QWORD
T}
VPROLD	Bit Rotate Left
VPROLQ	Bit Rotate Left
VPROLVD	Bit Rotate Left
VPROLVQ	Bit Rotate Left
VPRORD	Bit Rotate Right
VPRORQ	Bit Rotate Right
VPRORVD	Bit Rotate Right
VPRORVQ	Bit Rotate Right
VPSCATTERDD	T{
Scatter Packed Dword, PackedQword with Signed Dword, Signed Qword Indices
T}
VPSCATTERDQ	T{
Scatter Packed Dword, PackedQword with Signed Dword, Signed Qword Indices
T}
VPSCATTERQD	T{
Scatter Packed Dword, PackedQword with Signed Dword, Signed Qword Indices
T}
VPSCATTERQQ	T{
Scatter Packed Dword, PackedQword with Signed Dword, Signed Qword Indices
T}
VPSHLD	T{
Concatenate and Shift Packed Data Left Logical
T}
VPSHLDV	T{
Concatenate and Variable Shift Packed Data Left Logical
T}
VPSHRD	T{
Concatenate and Shift Packed Data Right Logical
T}
VPSHRDV	T{
Concatenate and Variable Shift Packed Data Right Logical
T}
VPSHUFBITQMB	T{
Shuffle Bits From Quadword Elements Using Byte Indexes Into Mask
T}
VPSLLVD	T{
Variable Bit Shift Left Logical
T}
VPSLLVQ	T{
Variable Bit Shift Left Logical
T}
VPSLLVW	T{
Variable Bit Shift Left Logical
T}
VPSRAVD	T{
Variable Bit Shift Right Arithmetic
T}
VPSRAVQ	T{
Variable Bit Shift Right Arithmetic
T}
VPSRAVW	T{
Variable Bit Shift Right Arithmetic
T}
VPSRLVD	T{
Variable Bit Shift Right Logical
T}
VPSRLVQ	T{
Variable Bit Shift Right Logical
T}
VPSRLVW	T{
Variable Bit Shift Right Logical
T}
VPTERNLOGD	Bitwise Ternary Logic
VPTERNLOGQ	Bitwise Ternary Logic
VPTESTMB	Logical AND and Set Mask
VPTESTMD	Logical AND and Set Mask
VPTESTMQ	Logical AND and Set Mask
VPTESTMW	Logical AND and Set Mask
VPTESTNMB	Logical NAND and Set
VPTESTNMD	Logical NAND and Set
VPTESTNMQ	Logical NAND and Set
VPTESTNMW	Logical NAND and Set
VRANGEPD	T{
Range Restriction Calculation for Packed Pairs of Float64 Values
T}
VRANGEPS	T{
Range Restriction Calculation for Packed Pairs of Float32 Values
T}
VRANGESD	T{
Range Restriction Calculation From a Pair of Scalar Float64 Values
T}
VRANGESS	T{
Range Restriction Calculation From a Pair of Scalar Float32 Values
T}
VRCP14PD	T{
Compute Approximate Reciprocals of Packed Float64 Values
T}
VRCP14PS	T{
Compute Approximate Reciprocals of Packed Float32 Values
T}
VRCP14SD	T{
Compute Approximate Reciprocal of Scalar Float64 Value
T}
VRCP14SS	T{
Compute Approximate Reciprocal of Scalar Float32 Value
T}
VRCPPH	T{
Compute Reciprocals of Packed FP16 Values
T}
VRCPSH	T{
Compute Reciprocal of Scalar FP16 Value
T}
VREDUCEPD	T{
Perform Reduction Transformation on Packed Float64 Values
T}
VREDUCEPH	T{
Perform Reduction Transformation on Packed FP16 Values
T}
VREDUCEPS	T{
Perform Reduction Transformation on Packed Float32 Values
T}
VREDUCESD	T{
Perform a Reduction Transformation on a Scalar Float64 Value
T}
VREDUCESH	T{
Perform Reduction Transformation on Scalar FP16 Value
T}
VREDUCESS	T{
Perform a Reduction Transformation on a Scalar Float32 Value
T}
VRNDSCALEPD	T{
Round Packed Float64 Values to Include a Given Number of Fraction Bits
T}
VRNDSCALEPH	T{
Round Packed FP16 Values to Include a Given Number of Fraction Bits
T}
VRNDSCALEPS	T{
Round Packed Float32 Values to Include a Given Number of Fraction Bits
T}
VRNDSCALESD	T{
Round Scalar Float64 Value to Include a Given Number of Fraction Bits
T}
VRNDSCALESH	T{
Round Scalar FP16 Value to Include a Given Number of Fraction Bits
T}
VRNDSCALESS	T{
Round Scalar Float32 Value to Include a Given Number of Fraction Bits
T}
VRSQRT14PD	T{
Compute Approximate Reciprocals of Square Roots of Packed Float64 Values
T}
VRSQRT14PS	T{
Compute Approximate Reciprocals of Square Roots of Packed Float32 Values
T}
VRSQRT14SD	T{
Compute Approximate Reciprocal of Square Root of Scalar Float64 Value
T}
VRSQRT14SS	T{
Compute Approximate Reciprocal of Square Root of Scalar Float32 Value
T}
VRSQRTPH	T{
Compute Reciprocals of Square Roots of Packed FP16 Values
T}
VRSQRTSH	T{
Compute Approximate Reciprocal of Square Root of Scalar FP16 Value
T}
VSCALEFPD	T{
Scale Packed Float64 Values With Float64 Values
T}
VSCALEFPH	T{
Scale Packed FP16 Values with FP16 Values
T}
VSCALEFPS	T{
Scale Packed Float32 Values With Float32 Values
T}
VSCALEFSD	T{
Scale Scalar Float64 Values With Float64 Values
T}
VSCALEFSH	T{
Scale Scalar FP16 Values with FP16 Values
T}
VSCALEFSS	T{
Scale Scalar Float32 Value With Float32 Value
T}
VSCATTERDPD	T{
Scatter Packed Single, PackedDouble with Signed Dword and Qword Indices
T}
VSCATTERDPS	T{
Scatter Packed Single, PackedDouble with Signed Dword and Qword Indices
T}
VSCATTERQPD	T{
Scatter Packed Single, PackedDouble with Signed Dword and Qword Indices
T}
VSCATTERQPS	T{
Scatter Packed Single, PackedDouble with Signed Dword and Qword Indices
T}
VSHUFF32x4	T{
Shuffle Packed Values at 128-BitGranularity
T}
VSHUFF64x2	T{
Shuffle Packed Values at 128-BitGranularity
T}
VSHUFI32x4	T{
Shuffle Packed Values at 128-BitGranularity
T}
VSHUFI64x2	T{
Shuffle Packed Values at 128-BitGranularity
T}
VSQRTPH	T{
Compute Square Root of Packed FP16 Values
T}
VSQRTSH	T{
Compute Square Root of Scalar FP16 Value
T}
VSUBPH	Subtract Packed FP16 Values
VSUBSH	Subtract Scalar FP16 Value
VTESTPD	Packed Bit Test
VTESTPS	Packed Bit Test
VUCOMISH	T{
Unordered Compare Scalar FP16 Values and Set EFLAGS
T}
VZEROALL	T{
Zero XMM, YMM, and ZMM Registers
T}
VZEROUPPER	T{
Zero Upper Bits of YMM and ZMM Registers
T}
WAIT	Wait
WBINVD	T{
Write Back and Invalidate Cache
T}
WBNOINVD	T{
Write Back and Do Not Invalidate Cache
T}
WRFSBASE	Write FS/GS Segment Base
WRGSBASE	Write FS/GS Segment Base
WRMSR	T{
Write to Model Specific Register
T}
WRPKRU	T{
Write Data to User Page Key Register
T}
WRSSD	Write to Shadow Stack
WRSSQ	Write to Shadow Stack
WRUSSD	Write to User Shadow Stack
WRUSSQ	Write to User Shadow Stack
XABORT	Transactional Abort
XACQUIRE	T{
Hardware Lock Elision Prefix Hints
T}
XADD	Exchange and Add
XBEGIN	Transactional Begin
XCHG	T{
Exchange Register/Memory With Register
T}
XEND	Transactional End
XGETBV	T{
Get Value of Extended Control Register
T}
XLAT	Table Look-up Translation
XLATB	Table Look-up Translation
XOR	Logical Exclusive OR
XORPD	T{
Bitwise Logical XOR of Packed Double Precision Floating-Point Values
T}
XORPS	T{
Bitwise Logical XOR of Packed Single Precision Floating-Point Values
T}
XRELEASE	T{
Hardware Lock Elision Prefix Hints
T}
XRESLDTRK	Resume Tracking Load Addresses
XRSTOR	T{
Restore Processor Extended States
T}
XRSTORS	T{
Restore Processor Extended States Supervisor
T}
XSAVE	Save Processor Extended States
XSAVEC	T{
Save Processor Extended States With Compaction
T}
XSAVEOPT	T{
Save Processor Extended States Optimized
T}
XSAVES	T{
Save Processor Extended States Supervisor
T}
XSETBV	Set Extended Control Register
XSUSLDTRK	T{
Suspend Tracking Load Addresses
T}
XTEST	T{
Test if in Transactional Execution
T}
.TE

.SH SGX INSTRUCTIONS
.TS
allbox;
l l 
l l .
\fBMnemonic\fP	\fBSummary\fP
ENCLS	T{
Execute an Enclave System Function of Specified Leaf Number
T}
ENCLS	T{
Add a Page to an Uninitialized Enclave
T}
ENCLS	T{
Add a Page to an Initialized Enclave
T}
ENCLS	Mark a page in EPC as Blocked
ENCLS	T{
Create an SECS page in the Enclave Page Cache
T}
ENCLS	Read From a Debug Enclave
ENCLS	Write to a Debug Enclave
ENCLS	T{
Extend Uninitialized Enclave Measurement by 256 Bytes
T}
ENCLS	T{
Initialize an Enclave for Execution
T}
ENCLS	T{
Load an EPC Page and Mark its State
T}
ENCLS	T{
Load an EPC Page and Mark its State
T}
ENCLS	T{
Load an EPC Page and Mark its State
T}
ENCLS	T{
Load an EPC Page and Mark its State
T}
ENCLS	T{
Restrict the Permissions of an EPC Page
T}
ENCLS	Change the Type of an EPC Page
ENCLS	Add Version Array
ENCLS	T{
Read Type and Status Information About an EPC Page
T}
ENCLS	Remove a page from the EPC
ENCLS	Activates EBLOCK Checks
ENCLS	Activates EBLOCK Checks
ENCLS	T{
Invalidate an EPC Page and Write out to Main Memory
T}
ENCLU	T{
Execute an Enclave User Function of Specified Leaf Number
T}
ENCLU	Initialize a Pending Page
ENCLU	Accept Changes to an EPC Page
ENCLU	Decrements TCS.CSSA
ENCLU	Enters an Enclave
ENCLU	Exits an Enclave
ENCLU	Retrieves a Cryptographic Key
ENCLU	Extend an EPC Page Permissions
ENCLU	T{
Create a Cryptographic Report of the Enclave
T}
ENCLU	Re-Enters an Enclave
ENCLV	T{
Execute an Enclave VMM Function of Specified Leaf Number
T}
ENCLV	Decrement VIRTCHILDCNT in SECS
ENCLV	Increment VIRTCHILDCNT in SECS
ENCLV	T{
Set the ENCLAVECONTEXT Field in SECS
T}
.TE

.SH SMX INSTRUCTIONS
.TS
allbox;
l l 
l l .
\fBMnemonic\fP	\fBSummary\fP
GETSEC	Report the SMX Capabilities
GETSEC	T{
Execute Authenticated Chipset Code
T}
GETSEC	T{
Exit Authenticated Code Execution Mode
T}
GETSEC	Report the SMX Parameters
GETSEC	Enter a Measured Environment
GETSEC	Exit Measured Environment
GETSEC	SMX Mode Control
GETSEC	T{
Wake Up Sleeping Processors in Measured Environment
T}
.TE

.SH VMX INSTRUCTIONS
.TS
allbox;
l l 
l l .
\fBMnemonic\fP	\fBSummary\fP
INVEPT	T{
Invalidate Translations Derived from EPT
T}
INVVPID	T{
Invalidate Translations Based on VPID
T}
VMCALL	Call to VM Monitor
VMCLEAR	T{
Clear Virtual-Machine Control Structure
T}
VMFUNC	Invoke VM function
VMLAUNCH	Launch/Resume Virtual Machine
VMPTRLD	T{
Load Pointer to Virtual-Machine Control Structure
T}
VMPTRST	T{
Store Pointer to Virtual-Machine Control Structure
T}
VMREAD	T{
Read Field from Virtual-Machine Control Structure
T}
VMRESUME	Launch/Resume Virtual Machine
VMRESUME (1)	Resume Virtual Machine
VMWRITE	T{
Write Field to Virtual-Machine Control Structure
T}
VMXOFF	Leave VMX Operation
VMXON	Enter VMX Operation
.TE

.SH XEON PHI™ INSTRUCTIONS
.TS
allbox;
l l 
l l .
\fBMnemonic\fP	\fBSummary\fP
PREFETCHWT1	T{
Prefetch Vector Data Into Caches With Intent to Write and T1 Hint
T}
V4FMADDPS	T{
Packed Single Precision Floating-Point Fused Multiply-Add(4-Iterations)
T}
V4FMADDSS	T{
Scalar Single Precision Floating-Point Fused Multiply-Add(4-Iterations)
T}
V4FNMADDPS	T{
Packed Single Precision Floating-Point Fused Multiply-Add(4-Iterations)
T}
V4FNMADDSS	T{
Scalar Single Precision Floating-Point Fused Multiply-Add(4-Iterations)
T}
VEXP2PD	T{
Approximation to the Exponential 2^x of Packed Double Precision Floating-PointValues With Less Than 2^-23 Relative Error
T}
VEXP2PS	T{
Approximation to the Exponential 2^x of Packed Single Precision Floating-PointValues With Less Than 2^-23 Relative Error
T}
VGATHERPF0DPD	T{
Sparse PrefetchPacked SP/DP Data Values With Signed Dword, Signed Qword Indices Using T0 Hint
T}
VGATHERPF0DPS	T{
Sparse PrefetchPacked SP/DP Data Values With Signed Dword, Signed Qword Indices Using T0 Hint
T}
VGATHERPF0QPD	T{
Sparse PrefetchPacked SP/DP Data Values With Signed Dword, Signed Qword Indices Using T0 Hint
T}
VGATHERPF0QPS	T{
Sparse PrefetchPacked SP/DP Data Values With Signed Dword, Signed Qword Indices Using T0 Hint
T}
VGATHERPF1DPD	T{
Sparse PrefetchPacked SP/DP Data Values With Signed Dword, Signed Qword Indices Using T1 Hint
T}
VGATHERPF1DPS	T{
Sparse PrefetchPacked SP/DP Data Values With Signed Dword, Signed Qword Indices Using T1 Hint
T}
VGATHERPF1QPD	T{
Sparse PrefetchPacked SP/DP Data Values With Signed Dword, Signed Qword Indices Using T1 Hint
T}
VGATHERPF1QPS	T{
Sparse PrefetchPacked SP/DP Data Values With Signed Dword, Signed Qword Indices Using T1 Hint
T}
VP4DPWSSD	T{
Dot Product of Signed Words With Dword Accumulation (4-Iterations)
T}
VP4DPWSSDS	T{
Dot Product of Signed Words With Dword Accumulation and Saturation(4-Iterations)
T}
VRCP28PD	T{
Approximation to the Reciprocal of Packed Double Precision Floating-Point ValuesWith Less Than 2^-28 Relative Error
T}
VRCP28PS	T{
Approximation to the Reciprocal of Packed Single Precision Floating-Point ValuesWith Less Than 2^-28 Relative Error
T}
VRCP28SD	T{
Approximation to the Reciprocal of Scalar Double Precision Floating-Point ValueWith Less Than 2^-28 Relative Error
T}
VRCP28SS	T{
Approximation to the Reciprocal of Scalar Single Precision Floating-Point ValueWith Less Than 2^-28 Relative Error
T}
VRSQRT28PD	T{
Approximation to the Reciprocal Square Root of Packed Double PrecisionFloating-Point Values With Less Than 2^-28 Relative Error
T}
VRSQRT28PS	T{
Approximation to the Reciprocal Square Root of Packed Single PrecisionFloating-Point Values With Less Than 2^-28 Relative Error
T}
VRSQRT28SD	T{
Approximation to the Reciprocal Square Root of Scalar Double PrecisionFloating-Point Value With Less Than 2^-28 Relative Error
T}
VRSQRT28SS	T{
Approximation to the Reciprocal Square Root of Scalar Single Precision Floating-Point Value With Less Than 2^-28 Relative Error
T}
VSCATTERPF0DPD	T{
Sparse PrefetchPacked SP/DP Data Values with Signed Dword, Signed Qword Indices Using T0 Hint With Intentto Write
T}
VSCATTERPF0DPS	T{
Sparse PrefetchPacked SP/DP Data Values with Signed Dword, Signed Qword Indices Using T0 Hint With Intentto Write
T}
VSCATTERPF0QPD	T{
Sparse PrefetchPacked SP/DP Data Values with Signed Dword, Signed Qword Indices Using T0 Hint With Intentto Write
T}
VSCATTERPF0QPS	T{
Sparse PrefetchPacked SP/DP Data Values with Signed Dword, Signed Qword Indices Using T0 Hint With Intentto Write
T}
VSCATTERPF1DPD	T{
Sparse PrefetchPacked SP/DP Data Values With Signed Dword, Signed Qword Indices Using T1 Hint With Intentto Write
T}
VSCATTERPF1DPS	T{
Sparse PrefetchPacked SP/DP Data Values With Signed Dword, Signed Qword Indices Using T1 Hint With Intentto Write
T}
VSCATTERPF1QPD	T{
Sparse PrefetchPacked SP/DP Data Values With Signed Dword, Signed Qword Indices Using T1 Hint With Intentto Write
T}
VSCATTERPF1QPS	T{
Sparse PrefetchPacked SP/DP Data Values With Signed Dword, Signed Qword Indices Using T1 Hint With Intentto Write
T}
.TE

.SH COLOPHON
This UNOFFICIAL, mechanically-separated, non-verified reference is
provided for convenience, but it may be
incomplete or
broken in various obvious or non-obvious ways.
Refer to Intel® 64 and IA-32 Architectures Software Developer’s
Manual
\[la]https://software.intel.com/en\-us/download/intel\-64\-and\-ia\-32\-architectures\-sdm\-combined\-volumes\-1\-2a\-2b\-2c\-2d\-3a\-3b\-3c\-3d\-and\-4\[ra]
for anything serious.

.br
This page is generated by scripts; therefore may contain visual or semantical bugs. Please report them (or better, fix them) on https://github.com/MrQubo/x86-manpages.
