#!/usr/bin/env bash

# MIT License
#
# Copyright (c) 2020 Tersine Mühendisler Odası
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.


set -eu

FILE=$1
if [[ $FILE =~ /index.html$ ]] || [[ $FILE = index.html ]]; then
	is_index=1
else
	is_index=0
fi

# work on the temporary file
cp "$FILE" "$FILE.tmp"
FILE="$FILE.tmp"

# beautify html source
cat "$FILE" | htmlbeautifier -t 4 >"$FILE.beautiful"

# normalize rowspans
./rowspan-normalizer.sh "$FILE.beautiful"

# uglify html source (to remove line breaks)
cat "$FILE.beautiful" | html-minifier --collapse-whitespace >"$FILE.ugly"

# remove some unwanted tags
./tag-remover.sh "$FILE.ugly" header

# generate colophon
#SEEALSO="<h2>SEE ALSO</h2>x86-manpages(7) for a list of other x86-64 man pages."
#SEEALSO+="<br/><a href=\"https://www.felixcloutier.com/x86/${FILE}\">HTML version<a/>"
sed -i "s|This UNOFFICIAL|<h2>COLOPHON</h2> This UNOFFICIAL|" "$FILE.ugly"

# beautify the uglified
cat "$FILE.ugly" | htmlbeautifier -t 4 >"$FILE"

# convert html to markdown
pandoc -f html -t markdown_strict+pipe_tables --lua-filter=pandoc-filter.lua "$FILE" -o "$FILE.md"

# convert markdown to roff
cat "$FILE.md" | go-md2man >"$FILE.7"

# remove some chars
sed -i -e "s/ ¶//g" "$FILE.7" # delete this char
sed -i -e '/\\fB\\fC\\fR/d' "$FILE.7" # delete empty table rows

# Write header, date etc. to man page
if [[ $is_index = 1 ]]; then
	DATE="December 2023"                                            # Constant, from last processed intel manual
	NEW_TH=".TH \"X86-MANPAGES\" \"7\" \"$DATE\" \"Intel\" \"Intel x86-64 ISA Manual\""
	NAME='\n.SH NAME\nX86 AND AMD64 INSTRUCTION REFERENCE\n'
else
	TMP=$(grep "\.TH" "$FILE.7" | sed -e "s/.TH //")                # ".TH JMP — JUMP" --> "JMP — JUMP"
	TMP=$(echo -e "$TMP" | sed -e "s/\//-/g")                       # replace slashes with dash
	TITLE=$(echo -e "$TMP" | sed -e "s/ — /\n/g" | head -n 1)       # JMP
	HEADER=$(echo -e "$TMP" | sed -e "s/ — /\n/g" | tail -n 1)      # JUMP
	DATE="December 2023"                                            # Constant, from last processed intel manual
	NEW_TH=".TH \"X86-$TITLE\" \"7\" \"$DATE\" \"Intel\" \"Intel x86-64 ISA Manual\""
	NAME="\\n.SH NAME\\n$TITLE - $HEADER"
fi
sed -i "s/\.TH.*/$NEW_TH$NAME/" "$FILE.7" # replace line with new TH

# append to colophon
echo -e "\n.br\nThis page is generated by scripts; therefore may contain visual or semantical bugs. Please report them (or better, fix them) on https://github.com/MrQubo/x86-manpages." >>"$FILE.7"

if [[ $is_index = 1 ]]; then
	# Fix listing table.
	sed -i -z -e 's|\n\\\[la][^\n]*\.html\\\[ra]||g' "$FILE.7"
fi

# rename output
if [[ $is_index = 1 ]]; then
	TITLE_LOWERCASE=manpages
else
	TITLE_LOWERCASE=$(echo "$TITLE" | tr '[:upper:]' '[:lower:]' | sed "s/ //g") # remove space in filename
fi
# this loop is needed to generate e.g. 4 seperate files for "VSCATTERPF0DPS-VSCATTERPF0QPS-VSCATTERPF0DPD-VSCATTERPF0QPD" page
mkdir -p man7
for i in $(echo $TITLE_LOWERCASE | sed "s/-/\n/g"); do
        OUTPUT="man7/x86-$i.7"
        cp "$FILE.7" $OUTPUT
        echo "Done $OUTPUT"
done

# remove artifacts
rm "$FILE.7" "$FILE.beautiful" "$FILE.ugly" "$FILE.md" "$FILE"

#man -l "$OUTPUT"
