name: CI for Nix Updates

on:
  push:
    branches:
      - master

jobs:
  update-nix:
    runs-on: ubuntu-latest

    steps:
      - name: Install Nix
        uses: cachix/install-nix-action@08dcb3a5e62fa31e2da3d490afc4176ef55ecd72  # @v30
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Install dependencies from nixpkgs
        run: |
          nix-build '<nixpkgs>' -A bashNonInteractive -A nix-update --no-out-link

      - name: Checkout nix branch
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9  # @v3
        with:
          ref: nix

      - name: Set up Git
        run: |
          git config --local user.name "GitHub Action"
          git config --local user.email "action@github.com"

      - name: Run update script
        run: |
          ./update.sh

      - name: Commit changes
        run: |
          git add .
          git commit -m "Update from CI" || echo "No changes to commit"

      - name: Push changes to nix branch
        run: |
          git push origin nix --force
